import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getPackages } from "../services/packages";

interface Product {
  title: string;
  itinerary: string;
  description: string;
  thumbnail: string;
  price: number;
  popularity: number;
}

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]);
  const [product, setProduct] = useState<Product | null>(null);
  const HandleShowProducts = () => {
    getPackages().then(setProducts);
  };
  return (
    <>
      <Head>
        <title>7 Llamas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>7 Llamas</h1>
        <button
          className={styles.burronShowProducts}
          onClick={HandleShowProducts}
        >
          Mostrar Productos
        </button>
        <div className={styles.container}>
          {products.map((product, index) => (
            <div
              className={styles.item}
              key={index}
              onClick={() => setProduct(product)}
            >
              <div style={{ width: "100%", height: 250, position: "relative" }}>
                <Image
                  src={product.thumbnail}
                  alt={product.description}
                  layout="fill"
                  objectFit="cover"
                />
              </div>
              <div className={styles.content}>
                <h3>{product.title}</h3>
                <p className={styles.description}>{product.description}</p>
              </div>
            </div>
          ))}
        </div>
        {product !== null && (
          <div className={styles.modal}>
            <div className={styles.modalContent}>
              <h2>{product?.title}</h2>
              <button
                style={{
                  float: "right",
                  marginTop: "-30px",
                  padding: 5,
                  borderRadius: 8,
                }}
                onClick={() => setProduct(null)}
              >
                Cerrar
              </button>
              <div
                style={{
                  width: "100%",
                  height: 250,
                  position: "relative",
                  margin: "2rem 0",
                }}
              >
                <Image
                  src={product.thumbnail}
                  alt={product.description}
                  layout="fill"
                  objectFit="cover"
                />
              </div>
              <p>{product.description}</p>
            </div>
          </div>
        )}
      </main>
    </>
  );
}
