import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getEconomicPackages } from "../services/packages";

export default function Home() {
  const [products, setProducts] = useState<
    {
      itinerary: string;
      description: string;
      thumbnail: string;
      price: number;
      popularity: number;
    }[]
  >([]);
  const HandleShowProducts = () => {
    getEconomicPackages().then(setProducts);
  };
  return (
    <>
      <Head>
        <title>7 Llamas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>7 Llamas</h1>
        <button
          className={styles.burronShowProducts}
          onClick={HandleShowProducts}
        >
          Mostrar Productos
        </button>
        <div className={styles.container}>
          {products.map((product, index) => (
            <div className={styles.item} key={index}>
              <div style={{ width: "100%", height: 200, position: "relative" }}>
                <Image
                  src={product.thumbnail}
                  alt={product.description}
                  layout="fill"
                  objectFit="cover"
                />
              </div>
              <div className={styles.content}>
                <p>{product.description}</p>
                <p>{product.itinerary}</p>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
